feat: Activity component
codecon-dev/site pull request #29
Opened 2022-06-11 02:14 UTC by kaiofelipejs

wip

2022-06-13 19:19 UTC, gabrnunes reviewed
Não esquece de mudar os `px` pra `rem` haha

2022-06-13 19:19 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    color: #707070;
usar uma das cores que estão no `colors` ali, se não tiver pode usar alguma próxima dela haha

2022-06-13 19:19 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    * {
acho estranho usar o seletor global, pq precisou?

2022-06-13 19:19 UTC, gabrnunes commented on components/_ui/Activity/Activity.tsx
> +  function getSponsorImage(sponsor = '') {
isso aqui provavelmente vai vir do banco né? dai acho que conseguimos puxar direto do CMS o logo do Patrocinador, saca?

2022-06-14 16:54 UTC, kaiofelipejs commented on components/_ui/Activity/Activity.tsx
> +  function getSponsorImage(sponsor = '') {
Não sei hahaha, mas se for do banco o path completo, mais fácil ainda. Criei isso ai só para caso fosse imagens estáticas no projeto

2022-06-14 16:57 UTC, kaiofelipejs commented
> Ah, outra coisa que percebi! A ideia é que todo o card seja clicável @kaiofelipejs, vc consegue fazer isso? Pq sempre que a pessoa clicar ela vai pra mais detalhes da palestra em si

Dá para ser clicável sim. Mas como fica o cenário do workshop que tem um botão específico? 🤔

2022-06-14 17:58 UTC, gabrnunes commented
@kaiofelipejs por padrão faz o texto do titulo ser clicável, no workshop clica também no botão dai :)

2022-06-14 17:58 UTC, gabrnunes commented on components/_ui/Activity/Activity.tsx
> +  function getSponsorImage(sponsor = '') {
Isso, pode considerar o path completo vindo do banco, igual eu fiz na PR https://github.com/codecon-dev/site/pull/32

2022-06-15 16:14 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    * {
Entendi!

2022-06-15 16:29 UTC, kaiofelipejs commented
> @kaiofelipejs por padrão faz o texto do titulo ser clicável, no workshop clica também no botão dai :)

É obrigatório que tenha link tanto na palestra quanto no workshop?

2022-06-15 16:30 UTC, kaiofelipejs commented
> 



> Tava pensando aqui @kaiofelipejs, acho que seria legal ter um tooltipo em cima do logo do patrocinador e tbm em cima do nome de cada palestrante. Será que conseguimos usar o [Radix](https://www.radix-ui.com/docs/primitives/components/tooltip) nesse caso? Ou outra tbm, se tu quiser.

O próprio tooltip do browser não serve já? O que já vem com o atributo "title"

2022-06-15 16:32 UTC, gabrnunes commented
> > 
> 
> > Tava pensando aqui @kaiofelipejs, acho que seria legal ter um tooltipo em cima do logo do patrocinador e tbm em cima do nome de cada palestrante. Será que conseguimos usar o [Radix](https://www.radix-ui.com/docs/primitives/components/tooltip) nesse caso? Ou outra tbm, se tu quiser.
> 
> O próprio tooltip do browser não serve já? O que já vem com o atributo "title"

Acho zoado, ele quase nem aparece haha

2022-06-15 16:40 UTC, kaiofelipejs commented on components/_ui/Activity/Activity.module.scss
> +    & > [class*='LinkButton'] {
@gabrnunes não gostei de ter que fazer isso, mas não achei outro jeito inteligente. Alguma sugestão?

2022-06-15 16:41 UTC, kaiofelipejs commented
> 

Entendi. Podemos adicionar sim, mas pode ser em outro PR? Se não acho que vai ficar muita coisa aqui nesse

2022-06-15 16:42 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    & > [class*='LinkButton'] {
colocar o LinkButton dentro de um wrapper?

2022-06-17 11:20 UTC, gabrnunes requested changes

2022-06-17 11:20 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    color: #707070;
faltou essa cor aqui

2022-06-17 11:20 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    letter-spacing: 0.1em;
pq aqui vc usou o `em`?

2022-06-17 11:20 UTC, gabrnunes commented on components/_ui/Activity/Activity.tsx
> +  return <div className={styles.header}>{children}</div>;
```suggestion
  return <header className={styles.header}>{children}</header>;
```

o que acha?

2022-06-17 11:20 UTC, gabrnunes commented on components/_ui/Activity/Activity.tsx
> +    <div className={styles.activity}>
```suggestion
    <article className={styles.activity}>
```

o que acha?

2022-06-17 12:27 UTC, kaiofelipejs commented on components/_ui/Activity/Activity.module.scss
> +    letter-spacing: 0.1em;
porque era a unidade que estava no Figma

2022-06-17 12:29 UTC, gabrnunes commented on components/_ui/Activity/Activity.module.scss
> +    letter-spacing: 0.1em;
Ta bem!

2022-06-17 12:29 UTC, gabrnunes approved these changes

2022-06-17 12:30 UTC, gabrnunes commented
@kaiofelipejs quebrou o build pq vc abriu o `<article>` mas fechou como `</div>`

2022-06-17 12:31 UTC, kaiofelipejs commented
> @kaiofelipejs quebrou o build pq vc abriu o `<article>` mas fechou como `</div>`

Fiz o commit automatico pelo github... achei que ele era mais inteligente hahaha

2022-06-17 12:32 UTC, gabrnunes approved these changes

2022-06-17 12:34 UTC, merged