patrocinadores @ grid
codecon-dev/site pull request #43
Opened 2022-06-21 19:42 UTC by gabrnunes

Página de patrocinadores :)

2022-06-21 21:13 UTC, kaiofelipejs commented on components/patrocinadores/SponsorsGrid/SponsorsGrid.tsx
> +        {sponsors?.map(sponsor => {
💅🏽 

```suggestion
export default function SponsorsGrid({ sponsors = [] }: Props) {
  return (
    <section>
      <Grid>
        {sponsors.map(sponsor => {
```

2022-06-21 21:13 UTC, kaiofelipejs commented on components/patrocinadores/SponsorsGrid/SponsorsGrid.tsx
> +                  <a className={styles.sponsor} style={{ backgroundColor: sponsor.color.hex }}>
no styled-components esse estilo seria bem mais legal de fazer, só pra tu saber memo hehehehe

2022-06-21 23:44 UTC, gabrnunes commented on components/_ui/Footer/Footer.tsx
> +export default function Footer({ sponsors, hideSponsors }: Props) {
verdade, tenho que corrigir ali pra quando não tiver os `sponsors` tbm esconder tudo.

2022-06-21 23:58 UTC, gabrnunes commented on components/patrocinadores/SponsorsGrid/SponsorsGrid.tsx
> +        {sponsors?.map(sponsor => {
na verdade nem precisou, o `sponsors` é obrigatório nesse componente, só tirei o `?` haha

2022-06-21 23:58 UTC, gabrnunes commented on components/patrocinadores/SponsorsGrid/SponsorsGrid.tsx
> +                  <a className={styles.sponsor} style={{ backgroundColor: sponsor.color.hex }}>
hahahah, tô ligado

2022-06-22 01:08 UTC, kaiofelipejs requested changes

2022-06-22 01:08 UTC, kaiofelipejs commented on components/_ui/Footer/Footer.tsx
> +      {sponsors && (
Dessa forma, se tu receber um array vazio ele ainda irá renderizar, porque o array fazio é truthy

![image](https://user-images.githubusercontent.com/41922744/174921944-03955379-a86b-4ef3-9e93-1f8c7a44e605.png)
O ideal é validar o `length` dele

2022-06-22 11:59 UTC, gabrnunes commented on components/_ui/Footer/Footer.tsx
> +      {sponsors && (
Ah, mas tipo, nunca vai vir uma array vazia

2022-06-22 13:07 UTC, gabrnunes commented on components/_ui/Footer/Footer.tsx
> +      {sponsors && (
Se não tem nada cadastrado o CMS retorna undefined

2022-06-22 13:11 UTC, kaiofelipejs approved these changes

2022-06-22 13:15 UTC, merged