Code codes@login
codecon-dev/site pull request #72
Opened 2022-08-16 01:29 UTC by gabrnunes

2022-08-16 01:29 UTC, gabrnunes commented
@kaiofelipejs ainda não terminei, mas dá uma olhada como pensei em fazer, o que acha?

2022-08-17 20:44 UTC, Markkop requested changes
Nice work, let me know if these suggestions make sense <3

2022-08-17 20:44 UTC, Markkop commented on components/_ui/PrivateArea/PrivateArea.tsx
> +      });
Since you're already using an `async/await` function, what about not mixing it with `.then()`?

```suggestion
    const response = await fetch(`/api/login/check`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ email })
    })
    
    const json = await response.json()
    const { data: { user }, success, message } = json
    if (!success) {
      toast.error(message);
      return;
    }
    
    const firstName = user.name.split(' ')[0];

    window.localStorage.setItem('codeconEmail', user.email);
    window.localStorage.setItem('codeconFullName', user.name);
    window.localStorage.setItem('codeconFirstName', firstName);

    setUserData({ firstName, fullName: user.name, email: user.email });
    toast.success(message);
```

2022-08-17 20:44 UTC, Markkop commented on components/_ui/PrivateArea/PrivateArea.tsx
> +  );
What if you return early for this first conditional as you did with `isLoading`?

```suggestion

  if (userData) {
    return  <>{React.cloneElement(children, { data: userData })}</>
  }

  return (
      <>
        <p>Faça login para continuar</p>

        <form
          // eslint-disable-next-line @typescript-eslint/no-misused-promises
          onSubmit={async e => {
            await handleSubmit(e);
          }}
        >
          <input
            onChange={event => setEmail(event.target.value)}
            type={'email'}
            placeholder={'Email'}
            />
          <input type="submit" />
        </form>
      </>
  );
```

2022-08-17 21:13 UTC, Markkop approved these changes
Awesome

2022-08-17 22:44 UTC, kaiofelipejs commented on pages/game/code-codes/resgate.tsx
> +          <Claim />
O Claim não precisa obrigatoriamente das props firstName, fullName, email?

2022-08-17 22:44 UTC, kaiofelipejs commented on components/code-codes/Claim/Claim.tsx
> +      toast.error(result.error.message as string);
Existe esse `result.error.message`? Pelo que entendi só tem result.status ou result.message 🤔

2022-08-17 22:44 UTC, kaiofelipejs commented on components/_ui/PrivateArea/PrivateArea.tsx
> +    return <>{React.cloneElement(children, { ...userData })}</>;
```suggestion
    return React.cloneElement(children, { ...userData });
```

2022-08-17 22:44 UTC, kaiofelipejs commented on hooks/useIsLoggedIn.ts
> +export const useIsLoggedIn = (callback: (data?: ConfUser) => void) => {
Não entendi bem esse hook. Ele retorna se está em loading, mas executa um callback passando informações?

Talvez ficaria mais fácil ele apenas retornar as informações (incluindo loading) e vc tratar ela onde ele for chamado

2022-08-17 22:44 UTC, kaiofelipejs commented on pages/game/code-codes/index.tsx
> +export default function CodeCodesRanking({ rankUsers }: Props) {
Essa página vai mudar né? hahaha

![image](https://user-images.githubusercontent.com/41922744/185256545-2f117f01-02bd-442d-a5c2-d683f64b6748.png)

2022-08-18 17:41 UTC, gabrnunes commented on pages/game/code-codes/index.tsx
> +export default function CodeCodesRanking({ rankUsers }: Props) {
hahahah vai sim, não mexi nessa ainda

2022-08-18 17:41 UTC, gabrnunes commented on hooks/useIsLoggedIn.ts
> +export const useIsLoggedIn = (callback: (data?: ConfUser) => void) => {
pois é, depois desse comentário eu eprcebi que esse hooke é inútil e pode ser só um useState

2022-08-18 17:51 UTC, gabrnunes commented on pages/game/code-codes/resgate.tsx
> +          <Claim />
Era, mas tirei agora hahaha

2022-08-18 17:52 UTC, gabrnunes commented on components/code-codes/Claim/Claim.tsx
> +      toast.error(result.error.message as string);
Vix, na real isso eu peguei do do ano passado, acho que deve ser ul retorno da API que é assim né?

2022-08-18 17:52 UTC, gabrnunes commented on components/_ui/PrivateArea/PrivateArea.tsx
> +    return <>{React.cloneElement(children, { ...userData })}</>;
num dá bom assim

2022-08-19 21:12 UTC, galenodemelo requested changes

2022-08-19 21:12 UTC, galenodemelo commented on components/code-codes/Claim/Claim.tsx
> +};
Não é o mesmo que `ConfUser`?

2022-08-19 21:12 UTC, galenodemelo commented on components/code-codes/Claim/Claim.tsx
> +    })
Não precisa desestruturar o objeto, acho

```suggestion
async function claim(payload: CodecodesClaimPayload) {
  const response = await fetch('/api/codecodes/claim', {
    method: 'POST',
    body: JSON.stringify(payload)
```

2022-08-19 21:12 UTC, galenodemelo commented on components/code-codes/Claim/Claim.tsx
> +      toast.error(result.error.message as string);
Dá uma olhada como é o retorno da API e tipa o retorno pra evitar essa dúvida

2022-08-19 21:12 UTC, galenodemelo commented on components/code-codes/Ranking/Ranking.tsx
> +        <p className={styles.how}>
Imagino que você vai ajustar isso em seguida, né? Pois o `Ranking.module.scss` tá vazio e tal hahaha

![image](https://user-images.githubusercontent.com/20726950/185707447-2faa8055-b844-44d7-a164-332caf4cabd9.png)

2022-08-19 22:08 UTC, kaiofelipejs commented on components/_ui/PrivateArea/PrivateArea.tsx
> +    return <>{React.cloneElement(children, { ...userData })}</>;
ué, pq não?

2022-08-20 13:47 UTC, gabrnunes commented on components/_ui/PrivateArea/PrivateArea.tsx
> +    return <>{React.cloneElement(children, { ...userData })}</>;
agora deu certo, acho que eu tinha feito alguma cagada hah

2022-08-20 13:47 UTC, gabrnunes commented on styles/reset.scss
> +  //height: 100%;
boa!

2022-08-20 13:48 UTC, gabrnunes commented on styles/reset.scss
> +  //height: 100%;
problema é que assim ou da outra forma ele tá criando barra de rolagem se a página é menor, vou deixar sem mesmo

2022-08-20 13:49 UTC, gabrnunes commented on components/_ui/PrivateArea/PrivateArea.tsx
> +type LoginResponse = { data: { user: User }; success: boolean; message: string };
mas parece confuso eu importar um tipo de dentro do `/api` não? Acho que no fim nem vou usar em nenhum lugar isso, só aqui meso

2022-08-20 13:50 UTC, gabrnunes commented on components/_ui/PrivateArea/PrivateArea.module.scss
> +  background-repeat: no-repeat;
aqui ele até pode ser um componente, mas nos outros dois eles são classes modificadoras né? dai acho dificil haha

2022-08-20 13:52 UTC, gabrnunes commented on components/code-codes/Claim/Claim.tsx
> +};
tens razão, mas nesse caso aqui os campos tem que ser não obrigatórios por causa de uma gambiarra que eu fiz hahaha, será que é zoado colocar os do `ConfUser` não obrigatórios?

2022-08-20 13:53 UTC, gabrnunes commented on components/code-codes/Claim/Claim.tsx
> +    })
Eu vou fazer outro PR pra ajustar esses esquemas do Code-Codes pq não tá funcionando nem o Claim e nem o Ranking, vou até tirar essas paradas dessa PR

2022-08-21 20:00 UTC, galenodemelo commented on components/_ui/PrivateArea/PrivateArea.tsx
> +type LoginResponse = { data: { user: User }; success: boolean; message: string };
Não acho estranho visto que é algo dela mesmo, mas então deixa assim se só for usar aqui mesmo

2022-08-21 20:02 UTC, galenodemelo commented on components/code-codes/Claim/Claim.tsx
> +};
Vai ficar inconsistente, então melhor não. Não taria pra fazer assim?
```typescript
export default function CodecodesClaimForm(userData?: ConfUser) {
```

2022-08-21 20:03 UTC, galenodemelo approved these changes

2022-08-22 00:20 UTC, kaiofelipejs approved these changes

2022-08-22 11:46 UTC, merged