Escape room@final
codecon-dev/site pull request #81
Opened 2022-08-24 22:24 UTC by gabrnunes

Criando a tela final da Escape Room, pra contabilizar os pontos do code-codes e tbm sabermos quem a gente pode fazer o sorteio no final.

2022-08-25 19:31 UTC, Markkop approved these changes
LGTM

2022-08-26 22:08 UTC, galenodemelo commented on src/services/EscapeRoomService.ts
> +        if (!data) throw new Error('Dados do Code-Codes vieram vazios');
Só pra confirmar: não tem como dar `claim` duas vezes nesse código, tem? Não deveríamos validar o `created` pra garantir que é a primeira vez que ele passa por aqui, será?

2022-08-26 22:11 UTC, galenodemelo approved these changes

2022-08-30 00:00 UTC, Markkop requested changes

2022-08-30 00:00 UTC, Markkop commented on src/services/EscapeRoomService.ts
> +        const { data } = await CodeCodesService.claimCode(user, 'ESCAPEWJKOPEEZZ');
Bota o código no .env (mas acho que é bom mudar ele, pq vai ficar no histórico do git)

2022-08-30 20:17 UTC, gabrnunes commented on src/services/EscapeRoomService.ts
> +        if (!data) throw new Error('Dados do Code-Codes vieram vazios');
O Code-codes já faz essa validação e não deixa resgatar duas vezes o mesmo código

2022-08-30 20:23 UTC, gabrnunes commented on src/services/EscapeRoomService.ts
> +        const { data } = await CodeCodesService.claimCode(user, 'ESCAPEWJKOPEEZZ');
tava só vendo se vcs tão esperto

2022-08-30 20:34 UTC, merged