Modal de aceite de termos
codecon-dev/site pull request #89
Opened 2022-08-25 00:45 UTC by gabrnunes

CLOSES https://github.com/codecon-dev/site/issues/79

2022-08-25 19:30 UTC, Markkop approved these changes
LGTM

2022-08-26 22:20 UTC, galenodemelo requested changes

2022-08-26 22:20 UTC, galenodemelo commented on src/services/UserService.ts
> +        });
Você já tem a instância do usuário, não precisa buscar de novo

2022-08-26 22:20 UTC, galenodemelo commented on src/database/model/User.ts
> +        acceptedTerms: { type: DataTypes.BOOLEAN }
Essa coluna vai vir preenchida ou vai vir nula? É interessante colocar um valor padrão ou um `allowNull` se ela puder ficar nula (acredito que o primeiro caso é melhor)

2022-08-26 22:20 UTC, galenodemelo commented on components/_ui/PrivateArea/TermsModal/TermsModal.tsx
> +            .then(() => {
A confiança de que sempre vai retornar `success: true`

2022-08-26 22:20 UTC, galenodemelo commented on pages/api/login/accept-terms.ts
> +    await ApiResponse.withCurrentUserAndErrorHandler(
Será que precisaremos verificar nas telas se o usuário aceitou os termos?

2022-08-30 20:52 UTC, merged